services:
  web:
    build:
      dockerfile: Dockerfile
    mem_limit: 2g
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "python /app/init_db.py && python /app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bond_network

  postgres:
    image: postgres:17-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      retries: 5
    networks:
      - bond_network

networks:
  bond_network:
    driver: bridge

volumes:
  postgres_data:
