services:
  web:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - bond_network

  db:
    image: postgres:17-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - bond_network


networks:
  bond_network:
    driver: bridge

volumes:
  postgres_data: