# Generated by Django 5.1.5 on 2025-01-17 02:01

import bonds.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cval', models.CharField(max_length=12, validators=[bonds.models.validate_cval])),
                ('ison', models.CharField(max_length=255)),
                ('tval', models.DecimalField(decimal_places=2, max_digits=10, validators=[bonds.models.validate_positive])),
                ('pdcp', models.CharField(max_length=50)),
                ('regdt', models.DateField()),
                ('eico', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=255)),
                ('elei', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[bonds.models.validate_positive])),
                ('interest_frequency', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
